[package]
name = "server"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4.0"
reqwest = { version = "0.11", features = ["json"] }