[package]
name = "rust"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
argon2 = "0.5"
rand_core = "0.6"
password-hash = "0.5"
uuid = { version = "1", features = ["v4"] }
